# Generated by Django 5.0.3 on 2024-03-19 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dealsOwner', models.CharField(max_length=100)),
                ('CompanyName', models.CharField(max_length=100)),
                ('customerName', models.CharField(max_length=100)),
                ('mobileNumber', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('dealTitle', models.CharField(max_length=200)),
                ('expectedRevenue', models.FloatField()),
                ('expectedDate', models.CharField(max_length=100)),
            ],
        ),
    ]
